plugins {
    id 'org.sonarqube' version '6.0.1.5171'
}

sonar {
    properties {
        property 'sonar.host.url', 'https://sonarcloud.io'
        property 'sonar.organization', 'lydiagarcia03'
        property 'sonar.projectKey', 'lydiagarcia03_omni-sheet-vault'
        property 'sonar.projectName', 'omni-sheet-vault'
        property 'sonar.exclusions', '**/build/**,**/node_modules/**'
    }
}